version: 2
jobs:
  checkout_and_build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.4.1-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # run tests!
      - run:
          name: run tests
          command: rake test

  deploy:
    docker:
      - image: google/cloud-sdk:latest #iron/builder:1.9
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - setup_remote_docker
      - run: ./bump.sh icache icache.go && cd icache && go build
      - run: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t freeman1988/toptal_app:$(grep -Eo "[0-9]+\.[0-9]+\.[0-9]+" ./version.txt) .
      - run: docker push freeman1988/toptal_app

      - run: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json

#      - run:
#          name: Run gradle build
#          command: |
#            gcloud --quiet components update  # remove if using the google/cloud-sdk image
#            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
#            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
#            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
#            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
#
#      - run:
#          name: Deploy App
#          command:  VERSION=$(grep -Eo "[0-9]+\.[0-9]+\.[0-9]+" \
#                    SERVICE_URL="https://staging-worker.iron.io" AUTO_DEPLOY=1 STAGING=1 \
#                    kubectl patch deployment notejam -n notejam -p '{"spec":{"template":{"spec":{"containers":[{"name":"notejam","image":"freeman1988/toptal_app:'"$VERSION"'"}]}}}}'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_and_build
      - deploy:
          requires:
            - checkout_and_build
          filters:
            branches:
              only: master
