version: 2
jobs:
  checkout_and_build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      - run:
          name: run tests
          command: rake test

  deploy-production:
    docker:
      - image: google/cloud-sdk:latest
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
      - setup_remote_docker

      - run:
          name: Create image and push it
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t freeman1988/toptal_app:$CIRCLE_SHA1 .
            docker push freeman1988/toptal_app:$CIRCLE_SHA1
      - run:
          name: Auth in gcloud
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}

      - run:
          name: Deploy new image
          command: kubectl patch deployment notejam -n notejam -p '{"spec":{"template":{"spec":{"containers":[{"name":"notejam","image":"freeman1988/toptal_app:'"$CIRCLE_SHA1"'"}]}}}}'

  deploy-staging:
    docker:
      - image: google/cloud-sdk:latest
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
      - setup_remote_docker

      - run:
          name: Create image and push it
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t freeman1988/toptal_app:staging .
            docker push freeman1988/toptal_app:staging
      - run:
          name: Auth in gcloud
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}

      - run:
          name: Deploy new image
          command: kubectl patch deployment notejam -n notejam-staging -p '{"spec":{"template":{"spec":{"containers":[{"name":"notejam","image":"freeman1988/toptal_app:staging"}]}}}}'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_and_build
      - deploy-staging:
          requires:
            - checkout_and_build
          filters:
            branches:
              only: master
      - deploy-production:
          requires:
            - checkout_and_build
          filters:
            branches:
              only: production

